/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.senai.sp.jandira.ui;

import br.senai.sp.jandira.dao.PlanoDeSaudeDAO;
import javax.swing.JTable;

/**
 *
 * @author 22282114
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
        PlanoDeSaudeDAO.criarPlanosDeSaudeTeste();
        criarTabelaPlanosDeSaude();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonSair = new javax.swing.JButton();
        buttonAgenda = new javax.swing.JButton();
        buttonPaciente = new javax.swing.JButton();
        buttonMedicos = new javax.swing.JButton();
        buttonPlanosDeSaude = new javax.swing.JButton();
        panelPlanoDeSaude = new javax.swing.JPanel();
        scrollTblePlanosDeSaude = new javax.swing.JScrollPane();
        tablePlanosDeSaude = new javax.swing.JTable();
        buttonAdicionarPlanoDeSaude = new javax.swing.JButton();
        buttonDeletarPlanoDeSaude = new javax.swing.JButton();
        buttonEditarPlanoDeSaude = new javax.swing.JButton();
        buttonEspecialidades1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 250, 250));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SISTEMA DE AGENDAMENTO DE CONSULTAS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 15, 540, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/doutora (4).png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 0, 64, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1030, 70);

        buttonSair.setBackground(new java.awt.Color(250, 250, 250));
        buttonSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonSair.setForeground(new java.awt.Color(255, 0, 51));
        buttonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/opcao-de-sair.png"))); // NOI18N
        buttonSair.setText("SAIR");
        buttonSair.setToolTipText("");
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSair);
        buttonSair.setBounds(900, 110, 110, 60);

        buttonAgenda.setBackground(new java.awt.Color(250, 250, 250));
        buttonAgenda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/calendario.png"))); // NOI18N
        buttonAgenda.setText("AGENDA");
        buttonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgendaActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAgenda);
        buttonAgenda.setBounds(40, 110, 130, 60);

        buttonPaciente.setBackground(new java.awt.Color(250, 250, 250));
        buttonPaciente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/paciente.png"))); // NOI18N
        buttonPaciente.setText("PACIENTES");
        buttonPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPaciente);
        buttonPaciente.setBounds(180, 110, 130, 60);

        buttonMedicos.setBackground(new java.awt.Color(250, 250, 250));
        buttonMedicos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonMedicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/assistencia-medica.png"))); // NOI18N
        buttonMedicos.setText("MÉDICOS");
        buttonMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMedicosActionPerformed(evt);
            }
        });
        getContentPane().add(buttonMedicos);
        buttonMedicos.setBounds(320, 110, 130, 60);

        buttonPlanosDeSaude.setBackground(new java.awt.Color(250, 250, 250));
        buttonPlanosDeSaude.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonPlanosDeSaude.setForeground(new java.awt.Color(71, 158, 255));
        buttonPlanosDeSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/estetoscopio (1).png"))); // NOI18N
        buttonPlanosDeSaude.setText("PLANOS DE SAÚDE");
        buttonPlanosDeSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPlanosDeSaudeActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPlanosDeSaude);
        buttonPlanosDeSaude.setBounds(640, 110, 190, 60);

        panelPlanoDeSaude.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " PLANOS DE SAÚDE  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14), new java.awt.Color(51, 153, 255))); // NOI18N
        panelPlanoDeSaude.setToolTipText("Planos de Saúde");
        panelPlanoDeSaude.setLayout(null);

        tablePlanosDeSaude.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollTblePlanosDeSaude.setViewportView(tablePlanosDeSaude);

        panelPlanoDeSaude.add(scrollTblePlanosDeSaude);
        scrollTblePlanosDeSaude.setBounds(30, 30, 960, 230);

        buttonAdicionarPlanoDeSaude.setBackground(new java.awt.Color(250, 250, 250));
        buttonAdicionarPlanoDeSaude.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonAdicionarPlanoDeSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/add.png"))); // NOI18N
        buttonAdicionarPlanoDeSaude.setToolTipText("Adicionar novo plano de saúde");
        buttonAdicionarPlanoDeSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarPlanoDeSaudeActionPerformed(evt);
            }
        });
        panelPlanoDeSaude.add(buttonAdicionarPlanoDeSaude);
        buttonAdicionarPlanoDeSaude.setBounds(800, 380, 60, 60);

        buttonDeletarPlanoDeSaude.setBackground(new java.awt.Color(250, 250, 250));
        buttonDeletarPlanoDeSaude.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonDeletarPlanoDeSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/bin (1).png"))); // NOI18N
        buttonDeletarPlanoDeSaude.setToolTipText("Excluir novo plano de saúde");
        buttonDeletarPlanoDeSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeletarPlanoDeSaudeActionPerformed(evt);
            }
        });
        panelPlanoDeSaude.add(buttonDeletarPlanoDeSaude);
        buttonDeletarPlanoDeSaude.setBounds(940, 380, 60, 60);

        buttonEditarPlanoDeSaude.setBackground(new java.awt.Color(250, 250, 250));
        buttonEditarPlanoDeSaude.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonEditarPlanoDeSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/edit-text.png"))); // NOI18N
        buttonEditarPlanoDeSaude.setToolTipText("Editar um plano de saúde selecionado");
        buttonEditarPlanoDeSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarPlanoDeSaudeActionPerformed(evt);
            }
        });
        panelPlanoDeSaude.add(buttonEditarPlanoDeSaude);
        buttonEditarPlanoDeSaude.setBounds(870, 380, 60, 60);

        getContentPane().add(panelPlanoDeSaude);
        panelPlanoDeSaude.setBounds(10, 210, 1010, 450);

        buttonEspecialidades1.setBackground(new java.awt.Color(250, 250, 250));
        buttonEspecialidades1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonEspecialidades1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/estetoscopio.png"))); // NOI18N
        buttonEspecialidades1.setText("ESPECIALIDADES");
        buttonEspecialidades1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEspecialidades1ActionPerformed(evt);
            }
        });
        getContentPane().add(buttonEspecialidades1);
        buttonEspecialidades1.setBounds(460, 110, 170, 60);

        setBounds(0, 0, 1042, 707);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSairActionPerformed

    private void buttonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAgendaActionPerformed

    private void buttonPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPacienteActionPerformed

    private void buttonMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMedicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMedicosActionPerformed

    private void buttonAdicionarPlanoDeSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarPlanoDeSaudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAdicionarPlanoDeSaudeActionPerformed

    private void buttonPlanosDeSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPlanosDeSaudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPlanosDeSaudeActionPerformed

    private void buttonEspecialidades1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEspecialidades1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEspecialidades1ActionPerformed

    private void buttonDeletarPlanoDeSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeletarPlanoDeSaudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDeletarPlanoDeSaudeActionPerformed

    private void buttonEditarPlanoDeSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarPlanoDeSaudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEditarPlanoDeSaudeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionarPlanoDeSaude;
    private javax.swing.JButton buttonAgenda;
    private javax.swing.JButton buttonDeletarPlanoDeSaude;
    private javax.swing.JButton buttonEditarPlanoDeSaude;
    private javax.swing.JButton buttonEspecialidades1;
    private javax.swing.JButton buttonMedicos;
    private javax.swing.JButton buttonPaciente;
    private javax.swing.JButton buttonPlanosDeSaude;
    private javax.swing.JButton buttonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelPlanoDeSaude;
    private javax.swing.JScrollPane scrollTblePlanosDeSaude;
    private javax.swing.JTable tablePlanosDeSaude;
    // End of variables declaration//GEN-END:variables

    private void criarTabelaPlanosDeSaude() {
        tablePlanosDeSaude.setModel(PlanoDeSaudeDAO.getTabelModel());

        //Desativar o redimensionamento da JTABLE
        tablePlanosDeSaude.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        //Definir a largura de cada coluna
        tablePlanosDeSaude.getColumnModel().getColumn(0).setPreferredWidth(100);
        tablePlanosDeSaude.getColumnModel().getColumn(1).setPreferredWidth(400);
        tablePlanosDeSaude.getColumnModel().getColumn(2).setPreferredWidth(457);
        
        //impedir e/ou bloquear a movimentação das colunas
        tablePlanosDeSaude.getTableHeader().setReorderingAllowed(false);
        
        //bloquear a edição das céluas
        tablePlanosDeSaude.setDefaultEditor(Object.class, null);
        
    }

}
