/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.senai.sp.jandira.ui;

import br.senai.sp.jandira.dao.EspecialidadeDAO;
import javax.swing.JTable;

/**
 *
 * @author 22282114
 */
public class PanelEspecialidades extends javax.swing.JPanel {

    public PanelEspecialidades() {

        initComponents();
        criarTabelaEspecialidade();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEspecialidades = new javax.swing.JPanel();
        scrollEspecialidade = new javax.swing.JScrollPane();
        tableEspecialidade = new javax.swing.JTable();
        adicionarEspecialidade = new javax.swing.JButton();
        adicionarEspecialidade1 = new javax.swing.JButton();
        adicionarEspecialidade2 = new javax.swing.JButton();

        setLayout(null);

        panelEspecialidades.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " ESPECIALIDADES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14), new java.awt.Color(71, 158, 255))); // NOI18N
        panelEspecialidades.setToolTipText("Planos de Saúde");
        panelEspecialidades.setLayout(null);

        tableEspecialidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollEspecialidade.setViewportView(tableEspecialidade);

        panelEspecialidades.add(scrollEspecialidade);
        scrollEspecialidade.setBounds(30, 30, 960, 270);

        adicionarEspecialidade.setBackground(new java.awt.Color(250, 250, 250));
        adicionarEspecialidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/bin (1).png"))); // NOI18N
        panelEspecialidades.add(adicionarEspecialidade);
        adicionarEspecialidade.setBounds(930, 380, 60, 60);

        adicionarEspecialidade1.setBackground(new java.awt.Color(250, 250, 250));
        adicionarEspecialidade1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/add.png"))); // NOI18N
        adicionarEspecialidade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarEspecialidade1ActionPerformed(evt);
            }
        });
        panelEspecialidades.add(adicionarEspecialidade1);
        adicionarEspecialidade1.setBounds(790, 380, 60, 60);

        adicionarEspecialidade2.setBackground(new java.awt.Color(250, 250, 250));
        adicionarEspecialidade2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/editar.png"))); // NOI18N
        panelEspecialidades.add(adicionarEspecialidade2);
        adicionarEspecialidade2.setBounds(860, 380, 60, 60);

        add(panelEspecialidades);
        panelEspecialidades.setBounds(0, 0, 1010, 450);
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarEspecialidade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarEspecialidade1ActionPerformed

        DialogEspecialidade dialogEspecialiade = new DialogEspecialidade(null, true);
        dialogEspecialiade.setVisible(true);

        criarTabelaEspecialidade(); //refresh

        // TODO add your handling code here:
    }//GEN-LAST:event_adicionarEspecialidade1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarEspecialidade;
    private javax.swing.JButton adicionarEspecialidade1;
    private javax.swing.JButton adicionarEspecialidade2;
    private javax.swing.JPanel panelEspecialidades;
    private javax.swing.JScrollPane scrollEspecialidade;
    private javax.swing.JTable tableEspecialidade;
    // End of variables declaration//GEN-END:variables

    private void criarTabelaEspecialidade() {
        tableEspecialidade.setModel(EspecialidadeDAO.getTableModel());
        tableEspecialidade.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tableEspecialidade.getColumnModel().getColumn(0).setPreferredWidth(100);
        tableEspecialidade.getColumnModel().getColumn(1).setPreferredWidth(400);
        tableEspecialidade.getColumnModel().getColumn(2).setPreferredWidth(457);
        tableEspecialidade.getTableHeader().setReorderingAllowed(false);
        tableEspecialidade.setDefaultEditor(Object.class, null);
    }

}
