/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.senai.sp.jandira.ui;

import br.senai.sp.jandira.dao.PlanoDeSaudeDAO;
import br.senai.sp.jandira.model.PlanoDeSaude;
import br.senai.sp.jandira.model.TipoOperacao;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author 22282114
 */
public class PanelPlanosDeSaude extends javax.swing.JPanel {

    int linha;

    public PanelPlanosDeSaude() {
        initComponents();
        criarTabelaPlanosDeSaude();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPlanoDeSaude = new javax.swing.JPanel();
        scrollTblePlanosDeSaude1 = new javax.swing.JScrollPane();
        tablePlanosDeSaude1 = new javax.swing.JTable();
        buttonAdicionarPlanoDeSaude1 = new javax.swing.JButton();
        buttonDeletarPlanoDeSaude1 = new javax.swing.JButton();
        buttonEditarPlanoDeSaude1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1010, 450));
        setLayout(null);

        panelPlanoDeSaude.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " PLANOS DE SAÚDE  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14), new java.awt.Color(51, 153, 255))); // NOI18N
        panelPlanoDeSaude.setToolTipText("Planos de Saúde");
        panelPlanoDeSaude.setLayout(null);

        tablePlanosDeSaude1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollTblePlanosDeSaude1.setViewportView(tablePlanosDeSaude1);

        panelPlanoDeSaude.add(scrollTblePlanosDeSaude1);
        scrollTblePlanosDeSaude1.setBounds(30, 30, 960, 270);

        buttonAdicionarPlanoDeSaude1.setBackground(new java.awt.Color(250, 250, 250));
        buttonAdicionarPlanoDeSaude1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonAdicionarPlanoDeSaude1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/add.png"))); // NOI18N
        buttonAdicionarPlanoDeSaude1.setToolTipText("Adicionar novo plano de saúde");
        buttonAdicionarPlanoDeSaude1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarPlanoDeSaude1ActionPerformed(evt);
            }
        });
        panelPlanoDeSaude.add(buttonAdicionarPlanoDeSaude1);
        buttonAdicionarPlanoDeSaude1.setBounds(790, 380, 60, 60);

        buttonDeletarPlanoDeSaude1.setBackground(new java.awt.Color(250, 250, 250));
        buttonDeletarPlanoDeSaude1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonDeletarPlanoDeSaude1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/bin (1).png"))); // NOI18N
        buttonDeletarPlanoDeSaude1.setToolTipText("Excluir novo plano de saúde");
        buttonDeletarPlanoDeSaude1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeletarPlanoDeSaude1ActionPerformed(evt);
            }
        });
        panelPlanoDeSaude.add(buttonDeletarPlanoDeSaude1);
        buttonDeletarPlanoDeSaude1.setBounds(930, 380, 60, 60);

        buttonEditarPlanoDeSaude1.setBackground(new java.awt.Color(250, 250, 250));
        buttonEditarPlanoDeSaude1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonEditarPlanoDeSaude1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/senai/sp/jandira/img/editar.png"))); // NOI18N
        buttonEditarPlanoDeSaude1.setToolTipText("Editar um plano de saúde selecionado");
        buttonEditarPlanoDeSaude1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarPlanoDeSaude1ActionPerformed(evt);
            }
        });
        panelPlanoDeSaude.add(buttonEditarPlanoDeSaude1);
        buttonEditarPlanoDeSaude1.setBounds(860, 380, 60, 60);

        add(panelPlanoDeSaude);
        panelPlanoDeSaude.setBounds(0, 0, 1010, 450);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAdicionarPlanoDeSaude1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarPlanoDeSaude1ActionPerformed
        DialogPlanosDeSaude dialogPlanosDeSaude = new DialogPlanosDeSaude(null,
            true,
            TipoOperacao.ADICIONAR,
            null);
        dialogPlanosDeSaude.setVisible(true);

        criarTabelaPlanosDeSaude(); //refresh
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAdicionarPlanoDeSaude1ActionPerformed

    private void buttonEditarPlanoDeSaude1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarPlanoDeSaude1ActionPerformed

        linha = tablePlanosDeSaude1.getSelectedRow();

        if (linha != -1) {
            editar();
        } else {
            JOptionPane.showMessageDialog(
                this,
                "Por favor selecione o plano de saúde a ser alterado",
                "Planos De Saúde",
                JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_buttonEditarPlanoDeSaude1ActionPerformed

    private void buttonDeletarPlanoDeSaude1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeletarPlanoDeSaude1ActionPerformed

        //obtendo o indice da linha selecionado na tabela
        linha = tablePlanosDeSaude1.getSelectedRow();

        //verificando se a linha é diferente de -1 (Se foi selecionada ou não)
        if (linha != -1) {
            //excluir a linha do plano
            excluir();

        } else {
            JOptionPane.showMessageDialog(
                this,
                "Selecione o plano a ser excluído!",
                "Plano De Saúde",
                JOptionPane.ERROR_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDeletarPlanoDeSaude1ActionPerformed

    private void excluir() {

        int resposta = JOptionPane.showConfirmDialog(
                this,
                "Você confirma a exclusão do plano de Saúde selecionado?",
                "Plano De Saúde",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (resposta == 0) {

            PlanoDeSaudeDAO.excluir(getCodigo());
            criarTabelaPlanosDeSaude();
        }
    }

    private Integer getCodigo() {

        String codigoStr = tablePlanosDeSaude1.getValueAt(linha, 0).toString();
        return Integer.valueOf(codigoStr);

    }

    private void editar() {

        PlanoDeSaude planoDeSaude = PlanoDeSaudeDAO.getPlanoDeSaude(getCodigo());

        DialogPlanosDeSaude dialogPlanosDeSaude = new DialogPlanosDeSaude(
                null,
                true,
                TipoOperacao.ALTERAR,
                planoDeSaude
        );
        dialogPlanosDeSaude.setVisible(true);
        
        criarTabelaPlanosDeSaude();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionarPlanoDeSaude1;
    private javax.swing.JButton buttonDeletarPlanoDeSaude1;
    private javax.swing.JButton buttonEditarPlanoDeSaude1;
    private javax.swing.JPanel panelPlanoDeSaude;
    private javax.swing.JScrollPane scrollTblePlanosDeSaude1;
    private javax.swing.JTable tablePlanosDeSaude1;
    // End of variables declaration//GEN-END:variables

    private void criarTabelaPlanosDeSaude() {
        tablePlanosDeSaude1.setModel(PlanoDeSaudeDAO.getTabelModel());

        //Desativar o redimensionamento da JTABLE
        tablePlanosDeSaude1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        //Definir a largura de cada coluna
        tablePlanosDeSaude1.getColumnModel().getColumn(0).setPreferredWidth(100);
        tablePlanosDeSaude1.getColumnModel().getColumn(1).setPreferredWidth(400);
        tablePlanosDeSaude1.getColumnModel().getColumn(2).setPreferredWidth(457);

        //impedir e/ou bloquear a movimentação das colunas
        tablePlanosDeSaude1.getTableHeader().setReorderingAllowed(false);

        //bloquear a edição das céluas
        tablePlanosDeSaude1.setDefaultEditor(Object.class, null);

    }

}
